export const userInfo = {
    profileId: null,
    firstname: null,
    lastname:null,
    middlename:null,
    nickname:null,
    gender:null,
    email:null,
    primary_email:null,
    secondaryEmails: [],
    profile_id: null,
    passportCountries: ['Australia', 'Newzealand'],
    birthday:null,
    date_of_birth: null,
    bio: null,
    isLogin: true,
    fitnesslevel:null,
};