export const userInfo = {
    firstname: null, 
    lastname:null,
    middlename:null,
    nickname:null,  
    gender:null, 
    primary_email:null,
    secondaryEmails: [], 
    profile_id: null,
    passportCountries: ['Australia', 'Newzealand'],
    birthday:null,
    bio: null,
    isLogin: false,
    fitnesslevel: null,
}
