stages:
  - build
  - setup
  - test
  - deploy

tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

setup:
  stage: setup
  script:
    - git lfs pull
    - cd client
    - npm install
  cache:
    paths:
      - client/node_modules/
  artifacts:
    paths:
      - client/node_modules/

junit:
  stage: test
  script:
    - cd server
    - ./gradlew test

jest:
  stage: test
  script:
    - cd client
    - npm install
    - npm run test

deploy-test-server:
  stage: deploy
  only:
    refs:
      - development
  script:
    - cd server
    #Create jar file for the project
    - ./gradlew bootJar
    #Remove the previous folder where we stored jar file
    - rm -rf /home/gitlab-runner/test-server/
    #Make a new folder to store the new jar file
    - mkdir -p /home/gitlab-runner/test-server/
    #Copy everything that is in the jar file
    - cp -r ./build/libs /home/gitlab-runner/test-server
    #Remove the old sh file
    - rm -f /home/gitlab-runner/runTestServer.sh || true
    #Copy new sh file
    - cp ../deployment-scripts/tunTestServer.sh /home/gitlab-runner/runTestServer.sh
    #Run testServer
    - sudo systemctl restart testServer

deploy-test-client:
  stage: deploy
  only:
    refs:
      - development
  script:
    - cd client
    #Generate website file (html js and css files)
    - npm run build
    #Remove previous folder where we stored the website file
    - rm -rf /home/gitlab-runner/test-client
    #Make a new folder to store new website file
    - mkdir -p /home/gitlab-runner/test-client/
    #Copy everything that is in the website file
    - cp -r ./dist /home/gitlab-runner/test-client
    #Remove old sh file
    - rm -f /home/gitlab-runner/runTestClient.sh || true
    #Copy new sh file
    - cp ../development-scripts/runTestClient.sh /home/gitlab-runner/runTestClient.sh
    #Run testClient
    - sudo systemctl restart testClient

deploy-prod-server:
  stage: deploy
  only:
    refs:
      - master
  script:
    # Create jar file
    - cd server
    - ./gradlew bootJar
    # Move jar file to clean directory
    - rm -rf /home/gitlab-runner/prod-server/
    - mkdir -p /home/gitlab-runner/prod-server/
    - cp -r ./build/libs /home/gitlab-runner/prod-server
    # Update bash script and restart service
    - rm -f /home/gitlab-runner/runProdServer.sh || true
    - cp ../deployment-scripts/runProdServer.sh /home/gitlab-runner/runProdServer.sh
    - sudo systemctl restart prodServer

deploy-prod-client:
  stage: deploy
  only:
    refs:
      - master
  script:
    # Generate website files
    - cd client
    - npm run build-prod
    # Move artifact to clean directory
    - rm -rf /home/gitlab-runner/prod-client/
    - mkdir -p /home/gitlab-runner/prod-client/
    - cp -r ./dist /home/gitlab-runner/prod-client
    # Update bash script and restart service
    - rm -f /home/gitlab-runner/runProdClient.sh || true
    - cp ../deployment-scripts/runProdClient.sh /home/gitlab-runner/runProdClient.sh
    - sudo systemctl restart prodClient

